=== viktorpts/xml-coursework/LMS.xsd
<?xml version="1.0" encoding="utf-8" ?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

    <xsd:element name="Course">
        <xsd:complexType>
            <xsd:all>
                <xsd:element name="Name" type="xsd:string"></xsd:element>
                <xsd:element name="Description" type="xsd:string" minOccurs="0"></xsd:element>
                <xsd:element name="Category" type="xsd:string" minOccurs="0"></xsd:element>
                <xsd:element name="Level" minOccurs="0">
                    <xsd:simpleType>
                        <xsd:restriction base="xsd:string">
                            <xsd:enumeration value="Basic"></xsd:enumeration>
                            <xsd:enumeration value="Fundamentals"></xsd:enumeration>
                            <xsd:enumeration value="Advanced"></xsd:enumeration>
                            <xsd:enumeration value="Master"></xsd:enumeration>
                        </xsd:restriction>
                    </xsd:simpleType>
                </xsd:element>
                <xsd:element name="Instance" type="InstanceType"></xsd:element>
                <xsd:element name="Units" type="UnitListType"></xsd:element>
                <xsd:element name="Students" type="StudentListType"></xsd:element>
                <xsd:element name="Trainers" type="TrainerListType"></xsd:element>
            </xsd:all>
        </xsd:complexType>
    </xsd:element>

    <xsd:complexType name="InstanceType">
        <xsd:sequence>
            <xsd:element name="StartDateTime" type="xsd:dateTime"></xsd:element>
            <xsd:element name="EndDateTime" type="xsd:dateTime"></xsd:element>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="UnitListType">
        <xsd:sequence minOccurs="1" maxOccurs="unbounded">

            <xsd:element name="Unit">
                <xsd:complexType>
                    <xsd:all>
                        <xsd:element name="Name" type="xsd:string"></xsd:element>
                        <xsd:element name="Description" type="xsd:string" minOccurs="0"></xsd:element>
                        <xsd:element name="Instance" type="InstanceType"></xsd:element>
                        <xsd:element name="Resources" type="ResourceListType"></xsd:element>
                    </xsd:all>
                    <xsd:attribute name="order" type="xsd:integer" default="0"></xsd:attribute>
                </xsd:complexType>
            </xsd:element>

        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="ResourceListType">
        <xsd:sequence minOccurs="0" maxOccurs="unbounded">

            <xsd:element name="Resource">
                <xsd:complexType>
                    <xsd:all>
                        <xsd:element name="Name" type="xsd:string"></xsd:element>
                        <xsd:element name="URL" type="xsd:anyURI"></xsd:element>
                        <xsd:element name="IconURL" type="xsd:anyURI" minOccurs="0"></xsd:element>
                    </xsd:all>
                    <xsd:attribute name="order" type="xsd:integer" default="0"></xsd:attribute>
                    <xsd:attribute name="visible" type="xsd:boolean" default="true"></xsd:attribute>
                    <xsd:attribute name="type" type="ResourceTypeAttr" use="required"></xsd:attribute>
                </xsd:complexType>
            </xsd:element>

        </xsd:sequence>
    </xsd:complexType>

    <xsd:simpleType name="ResourceTypeAttr">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="video"></xsd:enumeration>
            <xsd:enumeration value="archive"></xsd:enumeration>
            <xsd:enumeration value="doc"></xsd:enumeration>
            <xsd:enumeration value="external"></xsd:enumeration>
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:complexType name="StudentListType">
        <xsd:sequence minOccurs="0" maxOccurs="unbounded">

            <xsd:element name="Student">
                <xsd:complexType>
                    <xsd:all>
                        <xsd:element name="FirstName" type="xsd:string"></xsd:element>
                        <xsd:element name="LastName" type="xsd:string"></xsd:element>
                        <xsd:element name="Email" type="xsd:string"></xsd:element>
                        <xsd:element name="Score" type="xsd:integer" minOccurs="0"></xsd:element>
                    </xsd:all>
                </xsd:complexType>
            </xsd:element>

        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="TrainerListType">
        <xsd:sequence minOccurs="0" maxOccurs="unbounded">

            <xsd:element name="Trainer">
                <xsd:complexType>
                    <xsd:all>
                        <xsd:element name="FirstName" type="xsd:string"></xsd:element>
                        <xsd:element name="LastName" type="xsd:string"></xsd:element>
                        <xsd:element name="Description" type="xsd:string" minOccurs="0"></xsd:element>
                        <xsd:element name="PhotoURL" type="xsd:anyURI" minOccurs="0"></xsd:element>
                    </xsd:all>
                    <xsd:attribute name="public" type="xsd:boolean" default="true"></xsd:attribute>
                </xsd:complexType>
            </xsd:element>

        </xsd:sequence>
    </xsd:complexType>

</xsd:schema>

=== viktorpts/xml-coursework/LMS_4.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>

<Course xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="LMS.xsd">
    <Name>Stream Test</Name>
    <Instance>
        <StartDateTime>2018-05-19T00:00:00</StartDateTime>
        <EndDateTime>2018-05-19T23:59:59</EndDateTime>
    </Instance>
    <Units>
        <Unit>
            <Name>Stream Test 1</Name>
            <Instance>
                <StartDateTime>2018-05-19T11:00:00</StartDateTime>
                <EndDateTime>2018-05-19T13:00:00</EndDateTime>
            </Instance>
            <Resources/>
        </Unit>
    </Units>
    <Trainers/>
    <Students/>
</Course>

=== viktorpts/xml-coursework/LMS_5.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>

<Course xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="LMS.xsd">
    <Name>Internal Meeting</Name>
    <Instance>
        <StartDateTime>2017-01-01T00:00:00</StartDateTime>
        <EndDateTime>2017-01-01T23:59:59</EndDateTime>
    </Instance>
    <Units>
        <Unit>
            <Name>Meeting - Marketing</Name>
            <Instance>
                <StartDateTime>2017-04-10T10:00:00</StartDateTime>
                <EndDateTime>2017-04-10T11:00:00</EndDateTime>
            </Instance>
            <Resources/>
        </Unit>
        <Unit>
            <Name>Meeting - Finance</Name>
            <Instance>
                <StartDateTime>2017-04-10T13:00:00</StartDateTime>
                <EndDateTime>2017-04-10T14:00:00</EndDateTime>
            </Instance>
            <Resources/>
        </Unit>
        <Unit>
            <Name>Meeting - Marketing</Name>
            <Instance>
                <StartDateTime>2017-04-20T10:00:00</StartDateTime>
                <EndDateTime>2017-04-20T11:00:00</EndDateTime>
            </Instance>
            <Resources/>
        </Unit>
        <Unit>
            <Name>Meeting - Marketing</Name>
            <Instance>
                <StartDateTime>2017-04-22T15:30:00</StartDateTime>
                <EndDateTime>2017-04-22T16:00:00</EndDateTime>
            </Instance>
            <Resources/>
        </Unit>
        <Unit>
            <Name>Meeting - CRM</Name>
            <Instance>
                <StartDateTime>2017-04-23T18:00:00</StartDateTime>
                <EndDateTime>2017-04-23T18:30:00</EndDateTime>
            </Instance>
            <Resources/>
        </Unit>
    </Units>
    <Trainers/>
    <Students/>
</Course>

=== viktorpts/xml-coursework/LMS_3.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>

<Course xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="LMS.xsd">
    <Name>Microsoft Excel Automation</Name>
    <Description><![CDATA[<p>В курса по Microsoft Excel Automation ще се запознаете с технологията Visual Basic for Application (VBA) и различни похвати за надграждане способностите на Microsoft Excel. В курса ще бъдат показани детайлни примери и разрешения, с които ще можете да извършвате допълнителни функции и действия. С Microsoft Excel Automation ще можете да разгърнете своите способности, използвайки VBA, за да създавате специфични решения и инструменти за вашата организация или бизнес.</p><p>В началото на курса, самите студенти ще изберете какво приложение да бъде разработено по време на практическите занятия. Обучението е изключително практически насочено и ще ви научи как да продължите да търсите информация и след приключването му, за да развивате своите приложения.</p>]]></Description>
    <Category>Software Skills</Category>
    <Level>Advanced</Level>
    <Instance>
        <StartDateTime>2020-01-23T00:00:00</StartDateTime>
        <EndDateTime>2020-03-28T23:59:59</EndDateTime>
    </Instance>
    <Units>
        <Unit order="10">
            <Name>Introduction to VBA</Name>
            <Instance>
                <StartDateTime>2020-01-23T19:00:00</StartDateTime>
                <EndDateTime>2020-01-23T22:00:00</EndDateTime>
            </Instance>
            <Resources/>
        </Unit>
        <Unit order="20">
            <Name>Simple Functions and Calculations</Name>
            <Instance>
                <StartDateTime>2020-01-30T19:00:00</StartDateTime>
                <EndDateTime>2020-01-30T22:00:00</EndDateTime>
            </Instance>
            <Resources/>
        </Unit>
        <Unit order="30">
            <Name>Conditional Logic</Name>
            <Instance>
                <StartDateTime>2020-02-06T19:00:00</StartDateTime>
                <EndDateTime>2020-02-06T22:00:00</EndDateTime>
            </Instance>
            <Resources/>
        </Unit>
        <Unit order="40">
            <Name>Loops</Name>
            <Instance>
                <StartDateTime>2020-02-13T19:00:00</StartDateTime>
                <EndDateTime>2020-02-13T22:00:00</EndDateTime>
            </Instance>
            <Resources/>
        </Unit>
        <Unit order="50">
            <Name>Workbook Elements</Name>
            <Instance>
                <StartDateTime>2020-02-20T19:00:00</StartDateTime>
                <EndDateTime>2020-02-20T22:00:00</EndDateTime>
            </Instance>
            <Resources/>
        </Unit>
        <Unit order="60">
            <Name>Events and Triggers</Name>
            <Instance>
                <StartDateTime>2020-02-27T19:00:00</StartDateTime>
                <EndDateTime>2020-02-27T22:00:00</EndDateTime>
            </Instance>
            <Resources/>
        </Unit>
        <Unit order="70">
            <Name>Application Controls</Name>
            <Instance>
                <StartDateTime>2020-03-05T19:00:00</StartDateTime>
                <EndDateTime>2020-03-05T22:00:00</EndDateTime>
            </Instance>
            <Resources/>
        </Unit>
        <Unit order="80">
            <Name>Workshop: Exam Preparation</Name>
            <Instance>
                <StartDateTime>2020-03-12T19:00:00</StartDateTime>
                <EndDateTime>2020-03-12T22:00:00</EndDateTime>
            </Instance>
            <Resources/>
        </Unit>
    </Units>
    <Trainers>
        <Trainer>
            <FirstName>Ален</FirstName>
            <LastName>Паунов</LastName>
            <Description><![CDATA[<p><strong>Ален</strong> е Директор Обучения на Software University. Въпреки че години работи в сферата на правните услуги, открива програмирането като своя страст, автоматизирайките редица процеси, с които работи. Един от най-мотивиращите преподаватели в Софтуерния Университет, Ален успява да предаде своите знания и страст към програмирането на всичките си студенти.</p>]]></Description>
            <PhotoURL>/assets/img/1076/nu3VLuAzdrbPAyP9.png</PhotoURL>
        </Trainer>
        <Trainer public="false">
            <FirstName>Десислава</FirstName>
            <LastName>Георгиева</LastName>
        </Trainer>
    </Trainers>
    <Students>
        <Student>
            <FirstName>Милена</FirstName>
            <LastName>Венедикова</LastName>
            <Email>m.venedikova@yourmail.com</Email>
        </Student>
        <Student>
            <FirstName>Ангел</FirstName>
            <LastName>Стоянов</LastName>
            <Email>a.stoyanov@yourmail.com</Email>
        </Student>
        <Student>
            <FirstName>Гергана</FirstName>
            <LastName>Спасова</LastName>
            <Email>g.spasova@yourmail.com</Email>
        </Student>
        <Student>
            <FirstName>Елена</FirstName>
            <LastName>Грънчарова</LastName>
            <Email>e.gryncharova@yourmail.com</Email>
        </Student>
        <Student>
            <FirstName>Пенка</FirstName>
            <LastName>Хаджиева</LastName>
            <Email>p.hadzhieva@yourmail.com</Email>
        </Student>
        <Student>
            <FirstName>Никола</FirstName>
            <LastName>Йорданов</LastName>
            <Email>n.jordanova@yourmail.com</Email>
        </Student>
        <Student>
            <FirstName>Мария</FirstName>
            <LastName>Николова</LastName>
            <Email>m.nikolova@yourmail.com</Email>
        </Student>
        <Student>
            <FirstName>Даниела</FirstName>
            <LastName>Живкова</LastName>
            <Email>d.zhivkova@yourmail.com</Email>
        </Student>
        <Student>
            <FirstName>Росица</FirstName>
            <LastName>Асенова</LastName>
            <Email>r.asenova@yourmail.com</Email>
        </Student>
        <Student>
            <FirstName>Йорданка</FirstName>
            <LastName>Пешева</LastName>
            <Email>j.pesheva@yourmail.com</Email>
        </Student>
        <Student>
            <FirstName>Александър</FirstName>
            <LastName>Симеонов</LastName>
            <Email>a.simeonov@yourmail.com</Email>
        </Student>
    </Students>
</Course>
